### ISSUE TITLE
Relative numbering for Overleaf

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [fjwillemsen/NativeOverleaf#12]
Hey!

I am using the Overleaf editor using the Vim keybindings and I will find very useful to have the possibility of use a relative numbering for the editor, just like it is implemented using [this Chrome extension](https://chrome.google.com/webstore/detail/relative-line-numbering-f/cpndkecejnblehgenlnogffaeekmkphh)

Any idea if this could be easily implemented in this project?

**Comment by fjwillemsen** [comment]
Hi, thank you for suggesting this. The extension you have linked to is deprecated as of last month. As there are various extensions for Overleaf, it would be ideal to directly support the use of extensions instead of copying their functionality. There is an open issue on this here: https://github.com/fjwillemsen/NativeOverleaf/issues/8. I'll close this for now.
