### ISSUE TITLE
Can't open app on macOS M1

### ISSUE THREAD

**Issue by smeingast** [fjwillemsen/NativeOverleaf#2]
Hey, I just downloaded the ARM version (1.3.1) for macOS and upon launching, I get the message:

"Overleaf” is damaged and can’t be opened. You should move it to the Bin.

Quick update: The x64 works

**Comment by fjwillemsen** [comment]
That's not ideal, have you tried downloading it again? Sometimes a network interruption can corrupt an app during download. Some also say restarting your Mac helps. In any case, I just rebuilt and re-uploaded for Mac, could you check if it works? I have an M1 Mac as well and it works.

**Comment by smeingast** [comment]
Hm, I dowloaded it multiple times now, but also with the new version I get the same error :/ 
<img width="261" alt="Screenshot 2022-07-30 at 16 52 44" src="https://user-images.githubusercontent.com/4977153/181919830-5e2292a1-e023-4086-8965-0be2f435a80f.png">

**Comment by fjwillemsen** [comment]
That's very annoying, and have you tried restarting your Mac? I don't have another Mac currently around to try this one, have more people experienced this issue?

**Comment by AnvarAtayev** [comment]
Hello, I get the same error sadly. (But thank you for your work, this looks great, I hope to get it working soon)

**Comment by fjwillemsen** [comment]
Thanks for chiming in, @AnvarAtayev. Weird that the M1 version doesn't work yet the X64 does. It looks like this has happened to others as well, due to a codesigning issue. Could either of you try the following?

- Go to the download in Finder
- Right-click > "open" (instead of double clicking the app)
- If there's an "open anyway" option, click that
- If there's not, close the dialog and right-click > "open" a second time
- See if there's an "open anyway" option now

If this doesn't work, could you try whether [downloading this](https://we.tl/t-Svu3qTNAU2) works? It's the same latest-version app, but compressed using Finder instead of ditto. Maybe the issue is in the compression.

**Comment by smeingast** [comment]
Hey. I tried all of your suggestions, including downloading the new file. None worked, unfortunately. :/

**Comment by fjwillemsen** [comment]
Apparently, this happened because I didn't codesign the app on my end, which was [resolved thanks to another Nativefier issue](https://github.com/nativefier/nativefier/issues/401). I have just released 1.3.2, in which I self-signed the Mac apps, which should work. I have added a [troubleshooting](https://github.com/fjwillemsen/NativeOverleaf#troubleshooting) section to the README which should be sufficient for issues you may still run into. Please let me know whether it works properly for both of you now (@smeingast @AnvarAtayev)!

**Comment by smeingast** [comment]
Yep, now it works, thanks for your effort! 😊

**Comment by AnvarAtayev** [comment]
Excellent, thank you for that. Much appreciated 👍🏽

**Comment by taprobane99** [comment]
same problem with latest version on M1 - finder unzipping but says it is damaged
