### ISSUE TITLE
Settings are broken / Extra menu items are gone

### ISSUE THREAD

**Issue by RhvdG** [fjwillemsen/NativeOverleaf#32]
Changes on Overleaf's end have caused (I assume) the extra menu items your wonderful app provides to go missing. I can no longer access them.

**Comment by fjwillemsen** [comment]
Thank you for reporting this issue! I had noticed this as well and will fix it ASAP.

**Comment by fjwillemsen** [comment]
I've been working on fixing this issue, and while I have found a way to reinsert the settings panel itself (as per the commit), the settings themselves still do not work. The problem seems to be that the SettingsController is not found. We previously got this by `angular.element("[ng-controller=SettingsController]").scope();`, but this does no longer work. Attempting to get it via the settings pane class `angular.element(document.querySelector(".settings")).scope();` does not work either. Does anyone have other ideas?

**Comment by reskes** [comment]
I’ve discovered that the settings controller has been relocated to the object _IdeController_.

`angular.element(document.querySelector("[ng-controller=IdeController]")).scope();`

However, it appears to have some issues. In my build, for instance, switching modes only works once before it breaks.

Additionally, the native Overleaf menu only appears after I’ve accessed the Overleaf menu twice.

Is this project still under development? I noticed that work on [nativefier](https://github.com/nativefier/nativefier) has unfortunately been discontinued.

**Comment by RhvdG** [comment]
I'm beginning to worry now... my setup with custom fonts and everything is near-perfect and I would hate to have to revert to vanilla web Overleaf. With Nativefier no longer being maintained, perhaps [Multi](https://github.com/kofigumbs/multi) should be considered? I have no clue when it comes to coding, or I would help out; I just want to get back to writing about Hegel.

**Comment by reskes** [comment]
I took a quick look at Multi. One issue I see with that is, that it only supports Mac. So it wouldn't really be a replacement option for NativeOverleaf-Users on other OS.

**Comment by fjwillemsen** [comment]
Hi all, apologies for not getting back earlier. I was very busy with papers myself, but I hope to fix and update Native Overleaf over the Christmas break - I'll keep you updated!

**Comment by fjwillemsen** [comment]
I've just released [1.9.1](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.9.1). Big thanks to @reskes for discovering that `IdeController` is now used instead of `SettingsController`! 
This version fixes the main issue discussed here: the settings menu now appears immediately as it should. The problem was that Overleaf switched to lazy loading of the settings form, so waiting for the settings form to be loaded sufficed.  

However, some settings are still broken, and I need your help to fix them.  
One important functionality that remains broken is that the view is not automatically updated when changing themes, even though the scope update is applied. This used to work perfectly fine before. I suspect Overleaf changed the way they watch the settings, but if anybody could look into this issue, it would be very much appreciated!

**Comment by fjwillemsen** [comment]
@RhvdG That's a shame, it works on my M1 Pro MacBook Pro. Perhaps the download became messed up? There is no checksum in there, so this can happen. You could try downloading it again. If that doesn't work, you can try to use right-clicking on the app and then open, this should reveal whether it's actually broken or it's a signing issue. Could you post the output of `codesign -dv --verbose=4 /Path/to/Overleaf.app`?

**Comment by RhvdG** [comment]
I tried that before, and just did so again. Here's the output you asked for:

`Executable=/Users/rh/Downloads/Overleaf-darwin-arm64/Overleaf.app/Contents/MacOS/Overleaf
Identifier=Electron
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=513 flags=0x20002(adhoc,linker-signed) hashes=13+0 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=852736
Hash type=sha256 size=32
CandidateCDHash sha256=fa0655f9fbbc0b8141d9925be56aaa9f7696e249
CandidateCDHashFull sha256=fa0655f9fbbc0b8141d9925be56aaa9f7696e24918fbfeab4b9572a19e2d3d1a
Hash choices=sha256
CMSDigest=fa0655f9fbbc0b8141d9925be56aaa9f7696e24918fbfeab4b9572a19e2d3d1a
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=16384
Executable Segment flags=0x1
Page size=4096
CDHash=fa0655f9fbbc0b8141d9925be56aaa9f7696e249
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none`

**Comment by fjwillemsen** [comment]
@RhvdG the self-signed certificate was expired, which caused this issue. It has been fixed in the just-released [1.9.2](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.9.2).

**Comment by RhvdG** [comment]
All good now, thanks a lot.

**Comment by YelovSK** [comment]
On the 1.9.2 version of the Windows build I have no custom menu options.

**Comment by fjwillemsen** [comment]
@YelovSK That's likely, recent changes to Overleaf have made it very hard to keep this project in good condition. I tried circumventing this, but it's hard as any change on Overleaf's side can cause a lot of issues. I'm aware that many people really like Native Overleaf and have been very happy with the positive feedback, so I am currently working on a completely new alternative that won't have these issues, and much more... I'll post in this thread when it's available!
