### ISSUE TITLE
Old build

### ISSUE THREAD

**Issue by RhvdG** [fjwillemsen/NativeOverleaf#33]
Relaunching NativeOverleaf a warning appears saying the app was built with an outdated version of Nativefier, and that this is a security risk. Perhaps a new build is in order? Who knows, this might also solve the settings bug.

**Comment by sambo57u** [comment]
Everyone is getting this message. Could we have some new builds please!

**Comment by nkapila6** [comment]
I was about to open an issue for this and saw your thread.

Facing this as well..
<img width="241" alt="image" src="https://github.com/fjwillemsen/NativeOverleaf/assets/12816113/b44fc93c-f0a3-4e2a-a0df-b18b0ea4b886">

**Comment by fjwillemsen** [comment]
Apologies for this message, I am aware of it, the reason lies with Nativefier. 
I've just launched a [new version of Native Overleaf (1.9.1)](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.9.1) that fixes this and some other issues, but the "old build detected" message will reappear after some time. Guess I'll just have to keep those updates coming!

**Comment by RhvdG** [comment]
Thanks a lot for the update!
