### ISSUE TITLE
Cannot login using SSO

### ISSUE THREAD

**Issue by nkapila6** [fjwillemsen/NativeOverleaf#34]
The SSO redirects me to my university page but it opens a new tab directly on Firefox instead of working in the Overleaf tab.

Any way to fix this?

**Comment by nkapila6** [comment]
I linked my SSO with another email ID to avoid the SSO page altogether which seems to be a much easier workaround.

**Comment by fjwillemsen** [comment]
Hi @nkapila6, I understand you circumvented the problem. I've solved this earlier by adding some institutions explicitly (see #3), so if you want I can still add yours, but your approach is probably best to keep it if it works. I'm closing this for now, but feel free to reopen if you want your institution added. If so, please provide the URL of your institutional login in your reply.

**Comment by nkapila6** [comment]
Hi @fjwillemsen, thanks for the update!

Here's the URL: https://sso.gatech.edu/cas/login

**Comment by nkapila6** [comment]
Just a thought, possibly you could check if the domains end with .edu? 
This way the login happens through the "Chromium instance" (lets say) of the application and not through an external browser.

**Comment by fjwillemsen** [comment]
The [regex](https://github.com/fjwillemsen/NativeOverleaf/blob/4ddeb34db41e9855cdc104f0703fa6097bd181b7/compile-all.sh#L60) already matches all top-level domains, it just checks whether it contains something like login in the path. I'll add `sso` though because that's a nice one to match with as well.

**Comment by fjwillemsen** [comment]
I've just added this as you can see in the linked commit. I won't release a new version right now because I suspect I'll have to do that soon anyway, so if you could check whether this works once the new version is out, that would be nice.

**Comment by nkapila6** [comment]
@fjwillemsen Sure, I will. Just ping here once you release and I will test it out for you.

**Comment by nkapila6** [comment]
Hi @fjwillemsen, it still does not work.

How to regenerate the bug:

- I open Overleaf.
- Click on Login with SSO
- Enter my Gatech e-mail and password.
- This takes me to my MFA service which is Duo. This is where it redirects to the browser.
- This is not a simple one-time password as it requires you to approve logins on the phone. Similar to how Google works.

**A demo** 
https://youtu.be/KBROu8DcfVg

**This is how the URL looks like**
https://api-4b6bfd4c.duosecurity.com/frame/v4/auth/prompt?sid={REMOVED}

**My thoughts on this**
OK, you fix it for my university but what if another university's MFA service is different?
But then, I feel there are very limited number of services: Duo, MS Authenticator, Google, etc
Something I found on Google: https://expertinsights.com/insights/the-top-multi-factor-authentication-mfa-solutions-for-business/

**Comment by fjwillemsen** [comment]
Thanks for trying and giving your thoughts! 
The problem with adding all those listed is that I can't know the URL the all of those without people using that service telling me, and the URL may be changed later on. I can also not just treat every URL as an internal URL, because when people click links within Overleaf (e.g. in a document or a chat), this needs to be treated as an external URL. However, I have just added several new clauses to the regex that should match Duo, MS Authenticator, Google Authenticator, etc. If even more are needed, people will simply need to request it with an issue. Your problem should now be fixed and will be included in the next release, closing for now.

**Comment by nkapila6** [comment]
Thanks @fjwillemsen for your efforts. I will test it when the new version is out.
