### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by kevinkarnani** [fjwillemsen/NativeOverleaf#6]
Hi,

I wanted to try this out after seeing you on Reddit. I was able to run the software on my M1 Macbook, but it will not let me log in via my Google account as I get the message "This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can try again to sign in." When this happens, I cannot even back out to try another option.

**Comment by fjwillemsen** [comment]
Hi Kevin, thanks for reaching out. I reproduced the issue and have set `--user-agent-honest` to fix this. This may cause other issues (which I would like to hear about) because now the internal browser will not identify as Chrome, but for now it works. This is included in the [latest release](https://github.com/fjwillemsen/NativeOverleaf/releases/latest) (v1.7.2). I'll close for now, if you are still unable to login feel free to reopen.
